import type { BoardState } from "@kanban/types";

export const testBoard = {
  id: "board-user-mvp",
  name: "Launch Plan",
  columns: [
    { id: "col-todo", statusKey: "todo", name: "To Do", position: 1000 },
    { id: "col-progress", statusKey: "in_progress", name: "In Progress", position: 2000 },
    { id: "col-review", statusKey: "in_review", name: "In Review", position: 3000 },
    { id: "col-closed", statusKey: "closed", name: "Closed", position: 4000 },
  ],
  cards: [
    {
      id: "card-brief",
      columnId: "col-todo",
      title: "Finalize campaign brief",
      description: "Tighten the positioning notes before the kickoff review.",
      dueDate: null,
      position: 1000,
      assigneeInitials: ["ML", "JR"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-research",
      columnId: "col-todo",
      title: "Audience and market research",
      description: "Summarize competitor offers and customer segments.",
      dueDate: null,
      position: 2000,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-budget",
      columnId: "col-todo",
      title: "Confirm budgets",
      description: "Validate paid channel budget ranges with finance.",
      dueDate: null,
      position: 3000,
      assigneeInitials: ["AC", "DN"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-copy",
      columnId: "col-progress",
      title: "Draft campaign messaging and copy",
      description: "Create first-pass copy blocks for the landing page.",
      dueDate: null,
      position: 1000,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-assets",
      columnId: "col-progress",
      title: "Finalize asset list and bill of material",
      description: "Collect required creative, media, and placement assets.",
      dueDate: "2026-08-24",
      position: 2000,
      assigneeInitials: ["SP", "IM"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-channel",
      columnId: "col-progress",
      title: "Define channel strategy",
      description: "Prioritize launch channels and identify owners.",
      dueDate: null,
      position: 3000,
      assigneeInitials: ["NO", "LV"],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "shadow",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-kickoff",
      columnId: "col-progress",
      title: "Schedule kickoff meeting",
      description: "Find the launch planning slot and attach agenda notes.",
      dueDate: null,
      position: 4000,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-review",
      columnId: "col-review",
      title: "Review launch readiness checklist",
      description: "Check owners, due dates, risk notes, and handoffs.",
      dueDate: null,
      position: 1000,
      assigneeInitials: ["QS"],
      subtaskCount: 3,
      attachmentCount: 1,
      flagged: false,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-beta",
      columnId: "col-closed",
      title: "Customer beta interviews",
      description: "Interview notes are summarized for the launch team.",
      dueDate: null,
      position: 1000,
      assigneeInitials: ["ML", "JR"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-support",
      columnId: "col-closed",
      title: "Field marketing support plan",
      description: "Regional enablement plan is ready for distribution.",
      dueDate: null,
      position: 2000,
      assigneeInitials: ["KP", "RS", "IM"],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "waves",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-user-research",
      columnId: "col-closed",
      title: "User Research",
      description: "Research synthesis has been shared with the product team.",
      dueDate: null,
      position: 3000,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
    {
      id: "card-interview-process",
      columnId: "col-closed",
      title: "Customer interview process",
      description: "Interview guide and consent steps are documented.",
      dueDate: null,
      position: 4000,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 1,
      flagged: true,
      coverVariant: "none",
      createdAt: "2026-07-29T00:00:00Z",
      updatedAt: "2026-07-29T00:00:00Z",
    },
  ],
} satisfies BoardState;

export function cloneBoard(board: BoardState = testBoard): BoardState {
  return JSON.parse(JSON.stringify(board)) as BoardState;
}

export function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    status,
  });
}

export function emptyResponse() {
  return new Response(null, { status: 204 });
}
