import type { BoardState } from "@kanban/types";

export const initialBoard: BoardState = {
  id: "board-marketing-plan",
  name: "Launch Plan",
  columns: [
    { id: "col-todo", statusKey: "todo", name: "To Do", position: 0 },
    { id: "col-progress", statusKey: "in_progress", name: "In Progress", position: 1 },
    { id: "col-review", statusKey: "in_review", name: "In Review", position: 2 },
    { id: "col-closed", statusKey: "closed", name: "Closed", position: 3 },
  ],
  cards: [
    {
      id: "card-brief",
      columnId: "col-todo",
      title: "Finalize campaign brief",
      description: "Tighten the positioning notes before the kickoff review.",
      position: 0,
      assigneeInitials: ["ML", "JR"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
    },
    {
      id: "card-research",
      columnId: "col-todo",
      title: "Audience and market research",
      description: "Summarize competitor offers and customer segments.",
      position: 1,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
    },
    {
      id: "card-budget",
      columnId: "col-todo",
      title: "Confirm budgets",
      description: "Validate paid channel budget ranges with finance.",
      position: 2,
      assigneeInitials: ["AC", "DN"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
    },
    {
      id: "card-copy",
      columnId: "col-progress",
      title: "Draft campaign messaging and copy",
      description: "Create first-pass copy blocks for the landing page.",
      position: 0,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
    },
    {
      id: "card-assets",
      columnId: "col-progress",
      title: "Finalize asset list and bill of material",
      description: "Collect required creative, media, and placement assets.",
      dueDate: "2026-08-24",
      position: 1,
      assigneeInitials: ["SP", "IM"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
    },
    {
      id: "card-channel",
      columnId: "col-progress",
      title: "Define channel strategy",
      description: "Prioritize launch channels and identify owners.",
      position: 2,
      assigneeInitials: ["NO", "LV"],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "shadow",
    },
    {
      id: "card-kickoff",
      columnId: "col-progress",
      title: "Schedule kickoff meeting",
      description: "Find the launch planning slot and attach agenda notes.",
      position: 3,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
    },
    {
      id: "card-review",
      columnId: "col-review",
      title: "Review launch readiness checklist",
      description: "Check owners, due dates, risk notes, and handoffs.",
      position: 0,
      assigneeInitials: ["QS"],
      subtaskCount: 3,
      attachmentCount: 1,
      flagged: false,
      coverVariant: "none",
    },
    {
      id: "card-beta",
      columnId: "col-closed",
      title: "Customer beta interviews",
      description: "Interview notes are summarized for the launch team.",
      position: 0,
      assigneeInitials: ["ML", "JR"],
      subtaskCount: 4,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "none",
    },
    {
      id: "card-support",
      columnId: "col-closed",
      title: "Field marketing support plan",
      description: "Regional enablement plan is ready for distribution.",
      position: 1,
      assigneeInitials: ["KP", "RS", "IM"],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: false,
      coverVariant: "waves",
    },
    {
      id: "card-user-research",
      columnId: "col-closed",
      title: "User Research",
      description: "Research synthesis has been shared with the product team.",
      position: 2,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 0,
      flagged: true,
      coverVariant: "none",
    },
    {
      id: "card-interview-process",
      columnId: "col-closed",
      title: "Customer interview process",
      description: "Interview guide and consent steps are documented.",
      position: 3,
      assigneeInitials: [],
      subtaskCount: 0,
      attachmentCount: 1,
      flagged: true,
      coverVariant: "none",
    },
  ],
};
